FROM dockeratso/raspbian-dotnet-core-sdk-opencvsharp AS build-env

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

WORKDIR /app/out

USER root

ENTRYPOINT ["dotnet", "IotEdgeModule1.dll"]