FROM dockeratso/raspbian-dotnet-core-sdk-opencvsharp AS build-env

# Missing lib from base image
RUN apt update && apt install -y \
    libc6-dev \
    libgdiplus

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

WORKDIR /app/out

USER root

EXPOSE 5012

ENTRYPOINT ["dotnet", "IotEdgeModule1.dll"]